AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  weightmate

  SAM Template for weightmate

Globals:
  Function:
    Timeout: 3
Resources:
  WeightLambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: weight-lambda/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
      Events:
        WeightGet:
          Type: Api
          Properties:
            Path: /weight
            Method: get
            Cors:
              AllowMethods: "'*'"
              AllowHeaders: "'*'"
              AllowOrigin: "'*'"
        WeightPost:
          Type: Api
          Properties:
            Path: /weight
            Method: post
            Cors:
              AllowMethods: "'*'"
              AllowHeaders: "'*'"
              AllowOrigin: "'*'"
        WeightOptions: # Options must be handled for CORS
          Type: Api
          Properties:
            Path: /weight
            Method: options
            Cors:
              AllowMethods: "'*'"
              AllowHeaders: "'*'"
              AllowOrigin: "'*'"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild  
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: WeightmateUserPool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: WeightmateWeb
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

Outputs:
  WeightApi:
    Description: API Gateway endpoint URL for Prod stage for Weight function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/weight/"
  WeightLambdaFunction:
    Description: Weight Lambda Function ARN
    Value: !GetAtt WeightLambdaFunction.Arn
  WeightLambdaFunctionIamRole:
    Description: Implicit IAM Role created for Weight Lambda function
    Value: !GetAtt WeightLambdaFunctionRole.Arn
  UserPoolId:
    Description: ID of the User Pool
    Value: !Ref UserPool
  UserPoolClientId:
    Description: ID of the User Pool Client
    Value: !Ref UserPoolClient